# Generated by Django 5.0 on 2023-12-31 09:33

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="online_users",
            field=django_mysql.models.ListCharField(
                models.CharField(default="", max_length=16),
                default="",
                max_length=4335,
                size=255,
            ),
        ),
    ]
