# Generated by Django 5.0 on 2024-01-02 11:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about",
            field=ckeditor.fields.RichTextField(default="No About..."),
        ),
    ]
