# Generated by Django 4.2.9 on 2024-01-02 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_profile_about"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="about",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
    ]
