# Generated by Django 4.2.9 on 2024-01-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_profile_about_remove_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="no_picture.png", upload_to="avatars"),
        ),
    ]
